### ISSUE TITLE
Refactor data.py

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pvnet_app#109]
## Detailed Description
Current the `pvnet_app/data.py` has a lot of functions. It might be good to split this up

We current have
- download_all_sat_data
- _get_latest_time_and_mins_delay
- combine_5_and_15_sat_data
- extend_satellite_data_with_nans
- check_model_inputs_available
- preprocess_sat_data
- _download_nwp_data
- download_all_nwp_data
- regrid_nwp_data
- fix_ecmwf_data
- fix_ukv_data
- preprocess_nwp_data
- 

## Context
good to keep things clean
Might be good to wait for #108 

## Possible Implementation
We could split this into `pvnet_app/data/satellite.py` and `pvnet_app/data/nwp.py` file. 

Similiar for the tests

**Comment by DivyamAgg24** [comment]
Hi,
I hope this finds you well. I have created a branch named refactor-data.py and made the changes mentioned in this issue. The changes include creating a data folder and within in satellite.py and nwp.py with appropriate functions from data.py. The changes to imports in test_data.py have also been made

**Comment by peterdudfield** [comment]
Amazing @DivyamAgg24  - could you make a PR to this repo?

**Comment by DivyamAgg24** [comment]
I have created a pull request to this Repo

**Comment by peterdudfield** [comment]
Thank you @DivyamAgg24 for this
