### ISSUE TITLE
re-griding

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pvnet_app#25]
## Describe the bug
The regriding issue is causing an error on AWS

![Screenshot 2023-11-06 at 21 08 03](https://github.com/openclimatefix/pvnet_app/assets/34686298/95c7cfa8-8f3c-495a-bc99-62a48c322139)

## To Reproduce
1. re run task defintion 51 on AWS

## Expected behavior
For it to work and re grid the nwp data

## Additional context
There is a warning 

![Screenshot 2023-11-06 at 21 09 39](https://github.com/openclimatefix/pvnet_app/assets/34686298/bc4a8d3f-9aca-4024-b62e-10ad89858865)

Also had to add 
![Screenshot 2023-11-06 at 21 10 19](https://github.com/openclimatefix/pvnet_app/assets/34686298/8b8f13bc-630b-4170-a163-ef7b58e68b2e)

**Comment by peterdudfield** [comment]
now working, just need to deploy https://github.com/openclimatefix/ocf-infrastructure/pull/322

**Comment by dfulu** [comment]
Can we close this as completed @peterdudfield?

**Comment by peterdudfield** [comment]
Yea, close it
