### ISSUE TITLE
bug: pvnet app 0.0.22

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pvnet_app#35]
0.0.22 pvnet app doesnt run on AWS

![Screenshot 2024-01-26 at 17 37 38](https://github.com/openclimatefix/pvnet_app/assets/34686298/cde46d3c-c611-45c6-8fd2-16e288a6dbf2)

Also a bug on 0.0.20

![Screenshot 2024-01-29 at 10 22 50](https://github.com/openclimatefix/pvnet_app/assets/34686298/68412384-6aa2-41c2-9447-5d5185b6cb0e)

**Comment by dfulu** [comment]
From what I can tell this is due to unzip not being available. I've added this in #36 and hopefully that fixes the issue

**Comment by peterdudfield** [comment]
Unfortauntely still getting an error

![Screenshot 2024-01-29 at 13 02 41](https://github.com/openclimatefix/pvnet_app/assets/34686298/6697961b-d9d8-4eaf-a032-93178091d0b7)

**Comment by peterdudfield** [comment]
Now working on 0.0.23
