### ISSUE TITLE
Odd ECMWF PVnet results

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pvnet_app#50]
The current results from PVnet look a bit odd. 

Could the dropout fraction be a problem? 
https://huggingface.co/openclimatefix/pvnet_v2/blob/main/data_config.yaml#L14

What other issues could there be?

**Comment by dfulu** [comment]
Dropout fraction won't be the issue as dropout is only applied in training 
- https://github.com/openclimatefix/ocf_datapipes/blob/main/ocf_datapipes/training/common.py#L717

**Comment by peterdudfield** [comment]
is production definitely == True

**Comment by dfulu** [comment]
Is is - https://github.com/openclimatefix/pvnet_app/blob/main/pvnet_app/app.py#L226

And even if it weren't it would just mean we'd be looking for an init time 3 hours before t0 and the model was trained to handle that

**Comment by peterdudfield** [comment]
ah, whats the current delay on init time? I think we get 00:00 and 12:00 but they take ~6/7 to come in. Could this effect things?

**Comment by dfulu** [comment]
No that shouldn't have an effect. The model will work so long as there is NWP data with the required valid times. And it will just crash if the valid times are missing

**Comment by dfulu** [comment]
This seems to have been cleared up now so I'm going to close
