### ISSUE TITLE
Improve delay

### ISSUE THREAD

**Issue by dfulu** [openclimatefix/pvnet_app#56]
Currently the satellite delay logging is a timedelta object and can print slightly confusing messages. If the most recent satellite image is after the forecast init time t0 (t0 is the time we tell the model it can use data up. Currently this is 15 minutes before the run time) the logged message may look something like this: ```"5-min satellite delay is only -1 days +23:50:00" ``` which actually means the most recent satellite image was 10 minutes after t0. 

We should improve this logging just to print the delay minutes wrt t0, not the timedelta object.

## Context
This helps us monitor what is available to the app at the time of running, and helps us finetune how little of a delay we can get away with using when training the ML model.

## Possible Implementation

Area to look at is here: https://github.com/openclimatefix/pvnet_app/blob/main/pvnet_app/data.py#L55-L70

something like:
`f"5-min satellite delay is only {int(sat_delay_5.total_seconds()/60)} minutes - Using 5-minutely data."`

**Comment by DubraskaS** [comment]
#60 [https://github.com/DubraskaS/pvnet_app.git](url)

**Comment by DubraskaS** [comment]
#60

**Comment by DubraskaS** [comment]
Added my take on this first issue!

**Comment by dfulu** [comment]
Fixed by #60
