### ISSUE TITLE
Change how model repos are named

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/pvnet_app#66]
Currently, our model repos on Hugging Face are named in maybe confusing ways. `pvnet_v2` is the UK regional forecast model, for example. I propose a potentially clearer, more expandable way of naming our models and differentiating them:

<model_type>\_\<area>\_\<national/region/site>
i.e. pvnet_v2 would become pvnet_uk_region
PVNet for sites would be pvnet_uk_site
pvnet_india -> pvnet_india_region
windnet_india -> windnet_india_region
etc.
Summation model would be 
pvnet_uk_summation

**Comment by peterdudfield** [comment]
I think that would be sensible to do, if you change the repo name will the production system break?

**Comment by jacobbieker** [comment]
No, as we'll update them when we push a new model, so it doesn't make a difference then, we can leave the current one on pvnet2 just new ones would be on a different repo

**Comment by zakwatts** [comment]
Looks good to me.

**Comment by peterdudfield** [comment]
Ill close this, as we have renamed them in HF
