### ISSUE TITLE
Deploy GSP PVNet 36 hours

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pvnet_app#71]

**Comment by Sukh-P** [comment]
Merged a [PR](https://github.com/openclimatefix/pvnet_app/pull/86) to deploy the day ahead PVNet model, just need to do some terraform/other infra work to get it deployed, tested locally and able to get sensible looking outputs and saved some values to the DB.

**Comment by Sukh-P** [comment]
The terraform was updated [here](https://github.com/openclimatefix/ocf-infrastructure/pull/558/files) and [here](https://github.com/openclimatefix/ocf-infrastructure/pull/559) and we have now seen successful runs on dev and outputs on the analysis dashboard, will need to analyse outputs in more detail and monitor the deployment

**Comment by peterdudfield** [comment]
This is needed in order to turn the adjuster on https://github.com/openclimatefix/nowcasting-metrics/pull/45, `nowcasting_metrics=1.2.17`

**Comment by peterdudfield** [comment]
This will be the upgrade for the blend service - https://github.com/openclimatefix/uk-pv-forecast-blend/pull/31

**Comment by Sukh-P** [comment]
To complete this work we need sensible probabilistic outputs, hence a summation model for PVNet day ahead has been trained and uploaded to HF https://huggingface.co/openclimatefix/pvnet_summation_uk_national_day_ahead, will now work on deploying this model to dev

**Comment by Sukh-P** [comment]
This has been deployed to prod now, will monitor it runs okay for the rest of the day
